name: flutter_advanced_networkimage_example
description: Demonstrates how to use the flutter_advanced_networkimage_example plugin.

dependencies:
  flutter:
    sdk: flutter
  flutter_advanced_networkimage:
    path: ../

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"
